### ISSUE TITLE
Issues with ISO's that don't have ramdisk

### ISSUE THREAD

**Issue by tech101us** [jaxparrow07/Androidx86-Installer-Linux#6]
Doesn't seem to work with Androidx86 ISO's that don't include ramdisk.img

**Comment by jaxparrow07** [comment]
It was fixed in this commit and you won't face this issue in the upcoming build.
https://github.com/jaxparrow07/Androidx86-Installer-Linux/7cb98c6af771325ead2808e8dbcbe2d382fd94cf

https://github.com/jaxparrow07/Androidx86-Installer-Linux/blob/7cb98c6af771325ead2808e8dbcbe2d382fd94cf/app/main.py#L595

**Comment by jaxparrow07** [comment]
Fixed in the latest release.
